apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-docker
  name: python-docker
  namespace: rchk-test-rchk-dev
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: http-app
  selector:
    app: python-docker
status:
  loadBalancer: {}
